export default //const ExceptionCode = 
{
    HostNotReachable: 0,
    AccessDenied: 1,
    ResourceNotFound: 2,
    AttachDenied: 3,
    InvalidMethod: 4,
    InvokeDenied: 5,
    CreateDenied: 6,
    AddParentDenied: 7,
    AddChildDenied: 8,
    ViewAttributeDenied: 9,
    UpdateAttributeDenied: 10,
    StoreNotFound: 11,
    ParentNotFound: 12,
    ChildNotFound: 13,
    ResourceIsNotStore: 14,
    DeleteDenied: 15,
    DeleteFailed: 16,
    UpdateAttributeFailed: 17,
    GetAttributesFailed: 18,
    ClearAttributesFailed: 19,
    TemplateNotFound: 20,
    RenameDenied: 21,
    ClassNotFound: 22,
    MethodNotFound: 23,
    PropertyNotFound: 24,
    SetPropertyDenied: 25,
    ReadOnlyProperty: 26
};