export default //const ExceptionCode = 
{
    HostNotReachable: 0,
    AccessDenied: 1,
    UserNotFound: 2,
    ChallengeFailed: 3,
    ResourceNotFound: 4,
    AttachDenied: 5,
    InvalidMethod: 6,
    InvokeDenied: 7,
    CreateDenied: 8,
    AddParentDenied: 9,
    AddChildDenied: 10,
    ViewAttributeDenied: 11,
    UpdateAttributeDenied: 12,
    StoreNotFound: 13,
    ParentNotFound: 14,
    ChildNotFound: 15,
    ResourceIsNotStore: 16,
    DeleteDenied: 17,
    DeleteFailed: 18,
    UpdateAttributeFailed: 19,
    GetAttributesFailed: 20,
    ClearAttributesFailed: 21,
    TemplateNotFound: 22,
    RenameDenied: 23,
    ClassNotFound: 24,
    MethodNotFound: 25,
    PropertyNotFound: 26,
    SetPropertyDenied: 27,
    ReadOnlyProperty: 28
};